src/Entity/Driver.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DriverRepository")
 */
class Driver
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phone_number;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Rental", mappedBy="conducteur")
     */
    private $rentals;

    public function __construct()
    {
        $this->rentals = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    /**
     * @return Collection|Rental[]
     */
    public function getRentals(): Collection
    {
        return $this->rentals;
    }

    public function addRental(Rental $rental): self
    {
        if (!$this->rentals->contains($rental)) {
            $this->rentals[] = $rental;
            $rental->setConducteur($this);
        }

        return $this;
    }

    public function removeRental(Rental $rental): self
    {
        if ($this->rentals->contains($rental)) {
            $this->rentals->removeElement($rental);
            // set the owning side to null (unless already changed)
            if ($rental->getConducteur() === $this) {
                $rental->setConducteur(null);
            }
        }

        return $this;
    }
}

src/Form/DriverType.php
<?php

namespace App\Form;

use App\Entity\Driver;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DriverType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstName')
            ->add('lastName')
            ->add('phone_number')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Driver::class,
        ]);
    }
}

src/Controller/DriverController.php
<?php

namespace App\Controller;

use App\Entity\Driver;
use App\Form\DriverType;
use App\Repository\DriverRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/driver")
 */
class DriverController extends AbstractController
{
    /**
     * @Route("/", name="driver_index", methods={"GET"})
     */
    public function index(DriverRepository $driverRepository,Request $request): Response
    {
        $results=null;
        $driversearch=$request->request->get('driver_search');

        if($driversearch) {
            $results = $driverRepository->findByO($driversearch);

        }
        else{
            $results=$driverRepository->findAll();
        }
        return $this->render('driver/index.html.twig', [
            'drivers' => $results,
        ]);
    }

    /**
     * @Route("/new", name="driver_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $driver = new Driver();
        $form = $this->createForm(DriverType::class, $driver);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($driver);
            $entityManager->flush();

            return $this->redirectToRoute('driver_index');
        }

        return $this->render('driver/new.html.twig', [
            'driver' => $driver,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="driver_show", methods={"GET"})
     */
    public function show(Driver $driver): Response
    {
        return $this->render('driver/show.html.twig', [
            'driver' => $driver,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="driver_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Driver $driver): Response
    {
        $form = $this->createForm(DriverType::class, $driver);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('driver_index');
        }

        return $this->render('driver/edit.html.twig', [
            'driver' => $driver,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="driver_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Driver $driver): Response
    {
        if ($this->isCsrfTokenValid('delete'.$driver->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($driver);
            $entityManager->flush();
        }

        return $this->redirectToRoute('driver_index');
    }
}

templates/driver/_delete_form.html.twig
<form method="post" action="{{ path('driver_delete', {'id': driver.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ driver.id) }}">
    <button class="btn">Delete</button>
</form>

templates/driver/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/driver/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Driver{% endblock %}

{% block body %}
    <h1>Edit Driver</h1>

    {{ include('driver/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('driver_index') }}">back to list</a>

    {{ include('driver/_delete_form.html.twig') }}
{% endblock %}

templates/driver/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Driver index{% endblock %}

{% block body %}
    <h1>Driver index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Téléphone</th>
                <th>Nom et Prénom </th>

                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for driver in drivers %}
            <tr>
                <td>{{ driver.id }}</td>
                <td><a href="{{ path('driver_show', {'id': driver.id}) }}">{{ driver.phoneNumber }}</a></td>
                <td>{{ driver.lastName }} {{ driver.firstName }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('driver_new') }}">Create new</a>
{% endblock %}

templates/driver/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Driver{% endblock %}

{% block body %}
    <h1>Create new Driver</h1>

    {{ include('driver/_form.html.twig') }}

    <a href="{{ path('driver_index') }}">back to list</a>
{% endblock %}

templates/driver/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Driver{% endblock %}

{% block body %}
    <h1>Driver</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ driver.id }}</td>
            </tr>
            <tr>
                <th>FirstName</th>
                <td>{{ driver.firstName }}</td>
            </tr>
            <tr>
                <th>LastName</th>
                <td>{{ driver.lastName }}</td>
            </tr>
            <tr>
                <th>Phone_number</th>
                <td>{{ driver.phoneNumber }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('driver_index') }}">back to list</a>

    <a href="{{ path('driver_edit', {'id': driver.id}) }}">edit</a>

    {{ include('driver/_delete_form.html.twig') }}
{% endblock %}